#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]

# TODO: https://github.com/FROG3160/2025-reefscape/issues/1 
# Version of robotpy this project depends on
robotpy_version = "2025.3.1.1"

# Which extra RobotPy components should be installed
# -> equivalent to `pip install robotpy[extra1, ...]
robotpy_extras = [
    # "all",
    # "apriltag",
    "commands2",
    # "cscore",
    "navx",
    "pathplannerlib",
    # "phoenix5",
    #"photonvision",
    # "playingwithfusion",
    # "rev",
    # "romi",
    # "sim",
    # "xrp",
]

# Other pip packages to install
requires = [
    "phoenix6~=25.1",
    "photonlibpy",
    "robotpy-apriltag",
]